services:
  - type: web
    name: openhoop
    runtime: node
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.13.1
